# Generated by Django 5.1.1 on 2025-12-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Невідомий автор', max_length=255),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('wishlist', 'Хочу прочитати'), ('reading', 'Читаю'), ('read', 'Прочитано'), ('gifts', 'Для подарунків')], max_length=20),
        ),
    ]
